### PR TITLE
Creta port from RepRap & Marlin

### PR DESCRIPTION
**Pull request by ffnull**
Hi there. Im trying to make port of reprap firmware and Marlin 2.0.
But in Marlin im stuck on DUE hal, there is no match pins. Already trying MK4DUO, compiled without any issues but board doesnt start... Im have Da Vinci 2.0a DUO and i can be tester

### CODE REVIEW

**Comment by luc-github** [comment]
I think this PR is a mistake - you wanted to open issue instead ?

**Comment by ffnull** [comment]
Sorry. Yes

вс, 30 сент. 2018 г. в 22:34, Luc <notifications@github.com>:

**Comment by ffnull** [comment]
Can you give your email, that i can write you directly?

**Comment by luc-github** [comment]
Ok I close PR then

**Pull request closed without merging**
