### PR TITLE
Translated Japanese.

### PR DESCRIPTION
**Pull request by jp-96**
I translated Japanese, 100% maybe.

And I fixed 'page4' in src/ArduinoDUE/Repetier/uimenu.h, l.1432.

### CODE REVIEW

**Comment by luc-github** [comment]
Nice thank you. Will review soon

**Comment by luc-github** [comment]
@jp-96 I have reviewed and only change I see is Japanese must be translated - I need your help for this as I cannot do it 
Additionnaly please update your repository with the latest  .travis.yml - this will allow to pass the travis tests

**Comment by jp-96** [comment]
But, in general, Japanese can read simple English like 'Japanese'.
OK, I will change 'Japanese' to 'ﾆﾎﾝｺﾞ'

thanks.

**Comment by luc-github** [comment]
Cool thank you

**Comment by luc-github** [comment]
@jp-96 Merged, thank you and sorry for the delay

**Pull request merged**
